[package]
name = "gdbus"
version = "0.1.0"
authors = ["Antoni Boucher <bouanto@zoho.com>"]

[dependencies]
bitflags = "^0.7"
gio-sys = "^0.3"
glib = "^0.1"
glib-sys = "^0.3"
gobject-sys = "^0.3"
libc = "^0.2"

[dependencies.gdbus-sys]
path = "../gdbus-sys"

[dev-dependencies]
gtk = "^0.1"
